### ISSUE TITLE
couldn't alloc class smclightsensor

### ISSUE THREAD

**Issue by iamryanchia** [wujx1992/OSx86AppleEFI#2]
请问b85m d2v si可以用这个efi吗？用你的efi在这种主板上装，卡在了如题所示的地方，还请指导一下该如何解决，谢谢。

**Comment by wujx1992** [comment]
b85主板基本上差不多，你这个在config.plist里把Kernel->Add->SMCProcessor.kext、SMCSuperIO.kext、SMCLightSensor.kext,这三个kext删除或者设置为false(这3个是传感器)
<img width="589" alt="WX20201022-232156@2x" src="https://user-images.githubusercontent.com/11516980/96893897-c6b42000-14bd-11eb-829f-ece14e7bd85f.png">

**Comment by iamryanchia** [comment]
这三个都删除？刚才我把lightsensor删了，现在卡在`ioconsoleusers:gioscreenlockstate 3, hs 0, bs 0, now 0, sm 0x0`。我现在都删除试试，感谢！

**Comment by wujx1992** [comment]
你现在这个问题应该是核显不对，把注入的核显信息先删了
![1603380969001](https://user-images.githubusercontent.com/11516980/96895860-78a01c00-14bf-11eb-8df8-91050b39416f.jpg)

**Comment by iamryanchia** [comment]
已删，正在测试。

**Comment by iamryanchia** [comment]
已经装好进入系统了，非常感谢你的帮助，没想到回复的这么及时。请问分辨率有办法调节吗？显示器是2K的，看着比较糊。

**Comment by iamryanchia** [comment]
AMD的显卡

**Comment by wujx1992** [comment]
2k分辨率需要开启hidpi。
可以在github搜索one-key-hidpi，尝试这个脚本。

**Comment by iamryanchia** [comment]
好的，再次表达我的感谢(*￣︶￣)

**Comment by iamRyanChia** [comment]
> 你现在这个问题应该是核显不对，把注入的核显信息先删了
> ![1603380969001](https://user-images.githubusercontent.com/11516980/96895860-78a01c00-14bf-11eb-8df8-91050b39416f.jpg)

![Uploading 微信图片_20201023102240.jpg…]()
我的核显也是hd 4600，请问我该怎么改配置来适用我的核显？谢谢。

**Comment by iamryanchia** [comment]
> 你现在这个问题应该是核显不对，把注入的核显信息先删了
> ![1603380969001](https://user-images.githubusercontent.com/11516980/96895860-78a01c00-14bf-11eb-8df8-91050b39416f.jpg)

![hexian](https://user-images.githubusercontent.com/41557860/96949549-b8482180-151a-11eb-98f6-dc37ebd63458.jpg)
我的核显也是hd 4600，请问我该怎么改配置来适用我的核显？谢谢。

**Comment by wujx1992** [comment]
没必要特地的注入核显，whatevergreen已经帮忙做了。

**Comment by iamryanchia** [comment]
你好，今天看了hackintool的教程，修改了`config.plist`，核显通过关于本机->系统报告可以看到了，但是关于本机那儿还是显示的5MB。我怀疑是显示器接的独显导致没有显示正确的显存，但是把显示器接到核显的VGA接口又没有信号输出，独显是AMD R7 240，找不到驱动。请问你遇到过这种情况吗？谢谢。

**Comment by wujx1992** [comment]
下载使用最新的whatevergreen、bios核显设置正确，比研究这些教程靠谱多了，除非你真的懂。

**Comment by iamryanchia** [comment]
请问怎么更新whatevergreen呢？从GitHub下载最新的，然后直接替换掉Kexts文件夹里的文件可以吗？

**Comment by wujx1992** [comment]
就是这样
